<div class="container">
<div class="row">
<div class="col-md-12">
<div class="content_wrapper">
<div class="row">
<div class="col-lg-12">
<div class="price_area">
<h2><?=stripslashes($projects[0]['pricelist_heading']);?></h2>
<?=stripslashes($projects[0]['price_list_desc']);?>